### ISSUE TITLE
Images for Auth0 blog post

### ISSUE THREAD

**Issue by unicodeveloper** [unicodeveloper/Csharp-jwt-authentication-sample#1]
<img width="1280" alt="screen shot 2016-05-22 at 7 21 42 pm" src="https://cloud.githubusercontent.com/assets/2946769/15485354/a0851f58-2136-11e6-9194-e6383086beef.png">
<img width="1280" alt="screen shot 2016-05-22 at 7 22 27 pm" src="https://cloud.githubusercontent.com/assets/2946769/15485359/a4afa6f2-2136-11e6-862f-3063c10725d8.png">
<img width="1280" alt="screen shot 2016-05-22 at 7 22 40 pm" src="https://cloud.githubusercontent.com/assets/2946769/15485362/a9034074-2136-11e6-9e69-7d120b727192.png">
<img width="1280" alt="screen shot 2016-05-22 at 7 23 24 pm" src="https://cloud.githubusercontent.com/assets/2946769/15485367/ad9d9030-2136-11e6-9c05-18840fd11b50.png">
<img width="1280" alt="screen shot 2016-05-22 at 7 23 37 pm" src="https://cloud.githubusercontent.com/assets/2946769/15485370/b321e420-2136-11e6-8f36-a5094f26a98e.png">
<img width="1280" alt="screen shot 2016-05-22 at 7 25 39 pm" src="https://cloud.githubusercontent.com/assets/2946769/15485373/b8fe9618-2136-11e6-8729-495bae14f0fb.png">

**Comment by JNicholas2014** [comment]
Thanks for the Article and your work. I am having trouble building the cloned repository. The following error occurs when I attempt to open within VS 2015:

"The following error occurred attempting to run the project model server process (2.0.0).

Unable to start the Process. No executable found matching command 'dotnet-projectmodel-server'

I tried to restart VS and the same occurs. The message also states that I should check to see if .NET Core is properly installed. To the best of my knowledge it is, though this project isn't using .NET Core. I also have VS 2017 which does have .NET Core installed, but I have had no issues with it.
